Assembled the Bytes
Error still ocurring:
Buffer too small: capacity: 0, required: 1
com.esotericsoftware.kryo.KryoException: Buffer too small: capacity: 0, required: 1